### ISSUE TITLE
python logging 模块学习笔记

### ISSUE THREAD

**Issue by libijiang** [libijiang/blog#1]
# python logging 模块学习笔记

## 1、创建日志的基本步骤

1. 配置Logger（handlers、filters、formatters）
2. 通过`logging.getLogger()`函数获取Logger对象
3. 使用获取的Logger对象创建不同重要等级的消息，例如：`warn() info() debug() error() critiacal`

### 使用`logging.basicConfig()`完成配置

`logging.basicConfig()`函数参数

| 参数     | 含义                                                   |
| -------- | ------------------------------------------------------ |
| filename | 提供此项参数后日志直接输入到文件                       |
| filemode | 默认值为a，日志采用增量写入方式；w，新日志将会覆盖日志 |
| format   | 输出格式                                               |
| datefmt  | 日期格式                                               |
| level    | 日志等级                                               |

`basicConfig()`函数默认日志等级为WARNING，默认handler为输出到console，使用默认格式`%(levelname)s %(name)s %(message)s`并添加到根日志（root logger）

#### 输出日志到终端

```python
import logging
logging.warning('warning') #隐式调用logging.basicConfig()

#output
#WARNING:root:warning
```

如果使用`logging.basicConfig()`默认配置可以直接使用函数`warn() info() debug() error() critical()`,会自动调用`logging.basicConfig()`

#### 输出日志到文件

```python
import logging

logging.basicConfig(filename='audit.log',level=logging.DEBUG,format='%(asctime)s %(levelname)s %(message)s'，datefmt='%Y-%m-%d')
logging.warning('warning')

#output
#2017-12-31 WARNING warning
```

### 使用字典配置logging

```yaml
version: 1  #必须包含version值，目前合法值为1

handlers:
  auditFile:
    class: logging.FileHandler
    filename: audit.log
    encoding: utf-8
    formatter: basic
  console:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: basic

formatters:
  basic:
    format: "%(asctime)s\t%(levelname)s\t%(name)s\t%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

loggers:
  audit:
    handlers: [auditFile,console]
    level: INFO
    propagate: False
    #loggers的默认行为会将一条日志记录，从命名的Logger一直往上经过所有父级Logger直至根Logger， propagate: False将关闭传播规则。
root:
  handlers: [console]
  level: INFO

disable_existing_loggers: False
#保留所有在config.dictConfig()之前创建的Loggers
```

```python
import logging
import yaml

config=yaml.load(config)
logging.config.dictConfig(config)

logger=logging.getLogger('audit.main')
#所有以audit开头的日志记录器都会使用audit logger
logger.info('start')
```

### 模块Logger

```python
import logging
logger=logging.getLogger(__name__)
```

### 对象Logger

```python
import logging

class Card():
    def __init__(self,kind):
    	self.kind=kind
        self.logger=logging.getLogger("audit.{0}.{1}".format(self.__class__,self.kind))
        
c=Card('Birthday card')
c.logger.info('create card')
```

### 类Logger

```python
import logging

def logged(class_):
    class_.logger=logging.getLogger("{0}".format(class_))
    return class_

@logger
class Card():
    def send(self,sendTo):
        self.logger.info('send card to {0}'.format(sendTo))
```

### 函数Logger

```python
import logging

def main():
    log=logging.getLogger('main')
```

### 日志等级

| 日志模块变量 | 说明                   | 值   |
| ------------ | ---------------------- | ---- |
| DEBUG        | 用来诊断问题           | 10   |
| INFO         | 用来证明程序按预期运行 | 20   |
| WARN         | 警告（默认值）         | 30   |
| ERROR        | 错误，部分功能不能运行 | 40   |
| CRITICAL     | 严重错误，程序无法运行 | 50   |

### 扩展日志等级

```python
import logging

logging.addLevelName(15，'VERBOSE') #定义一个VERBOSE的日志等级值为15
logger.log(logging.VERBOSE,"message") #使用这个日志等级
```

### 创建消息

```python
logger.info('message') 
logger.warn('message')
logger.debug('message')
logger.error('message')
logger.critical('message')
```

## 5、例子

```python
import logging
import yaml

if name=="__main__":
    logging.config.dictConfig(yaml.load('config.yaml'))   #尽早配置logger
   
try:
    app=Main()
    status=app.run()
except Exception as e:
    logging.exception(e)
    status=2
finally:
    logging.shutdown()   #确保所有缓冲区都被刷新

sys.exit(status)
```

参考文档

> 《python 面向对象编程指南》Steven F.Lott 著
